### ISSUE TITLE
Flexibility for other bags and props to carry

### ISSUE THREAD

**Issue by mschaffr** [XakraD/xakra_backpacks#2]
Hey there :)

You can extend the config easily with a bone parameter like this.
```
    {
        Item = 'backpack5',
        Weight = 20,
        Model = 'p_bag01x',
        Position = vector3(0.45, 0.0, 0.0),
        Rotation = vector3(0.0, -90.0, -65.0),
        Bone = 'skel_l_hand',
    }
```

In the `client.lua:14` the parameter just need to be read.
```
    local BoneIndex = GetEntityBoneIndexByName(PlayerPedId(), data.Bone or "CP_Back")
```

With that you can use other bag props as well and connect it to the position you like, for example left hand like in the example.

Best regards

**Comment by XakraD** [comment]
I've already added it
